language: c
sudo: required
os:
    - linux
dist: bionic
git:
    submodules: false
compiler: clang
addons:
    apt:
        packages:
            - autoconf
            - autoconf2.13
            - autoconf2.64
            - automake
            - clang
            - libtool
            - m4
            - texinfo
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
            - yasm
script:
    - git submodule update --init --recursive --depth=50
    - (while sleep 1m; do date; done) &
    - (PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/wasm32/binutils-gdb.make >/dev/null 2>/dev/null) || PATH=/usr/local/bin:/usr/bin:/bin make -kj3 build/wasm32/binutils-gdb.make
