#!/bin/bash
set -o pipefail
set -o errexit
TMPD=$(mktemp -d --tmpdir wasmify.XXXXXXXXXX);
if [ x"$WASMDIR" = x ]; then
    WASMDIR=.
    export WASMDIR
fi
if [ x"$DELAY" = x ]; then
    DELAY=1
fi
cp "$1" $TMPD/elf
chmod u+rw $TMPD/elf
perl $WASMDIR/dyninfo/dyninfo.pl $TMPD/elf > $TMPD/dyninfo.json
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-elfedit $TMPD/elf --output-type=rel
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-objdump -hTRtrsj.data $TMPD/elf > $TMPD/dump0
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-objcopy --remove-relocations=.data --remove-relocations=.got -R .dynamic -R .dynsym -R .dynstr -R .rela.dyn -R .got.plt $TMPD/elf $TMPD/elf2
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-objdump -htrsj.data $TMPD/elf2 > $TMPD/dump2
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-objdump -htrsj.data $TMPD/elf2 > $TMPD/dump3
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-elfedit $TMPD/elf2 --output-type=rel
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-objcopy --remove-relocations=.got --remove-relocations=.data -R .dynamic -R .dynsym -R .dynstr -R .rela.dyn -R .got.plt $TMPD/elf2 $TMPD/elf3
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-objdump -htrsj.data $TMPD/elf3 > $TMPD/dump1
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-ld -nostdlibs -Map $TMPD/map1 -T $WASMDIR/lds/wasm32.cpp-lds.lds $TMPD/elf3 -o $TMPD/intermediate -N --warn-unresolved-symbols --no-check-sections 2>/dev/null
$WASMDIR/wasm32-unknown-none/bin/wasm32-unknown-none-ld -Map $TMPD/map2 -E -T $WASMDIR/lds/wasm32-wasmify.lds $TMPD/intermediate -o $TMPD/longwasm 2> /dev/null
$WASMDIR/bin/wasmrewrite $TMPD/longwasm > $TMPD/wasm
$WASMDIR/bin/wasmsect $TMPD/dyninfo.json > $TMPD/dyninfo.json.wass
cat $TMPD/dyninfo.json.wass >> $TMPD/wasm
cat $TMPD/wasm
