#!/usr/bin/bash
# find .git -name hooks | while read; do ln -sf ../../../../../git/hooks/pre-push "$REPLY"/pre-push; done
git submodule foreach --recursive sh -c '! (git remote | egrep '^pipcet$') || [ "$(git rev-parse 'pipcet/wasm')" = "$(git rev-parse 'HEAD')" ]'
