#!/bin/bash
if [ x"$WASMDIR" = x ]; then
    echo "WASMDIR needs to be set" > /dev/stderr
    exit 1
fi
TMPD="$(mktemp -d --tmpdir "run-elf-wasm32.XXXXXXXXXX")"
WASM="$TMPD/wasm"
shift PROG
"$WASMDIR/wasmify/wasmify-executable" "$PROG" > "$WASM"
exec "$WASMDIR/run/run-wasm" "$WASM" "$@"
