name: make all
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  all:
    name: make all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: git submodule update --init --recursive --
    - name: install texinfo, bison, flex
      run: sudo apt-get install texinfo bison flex
    - name: install GCC dependencies
      run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - name: make binutils-gdb
      run: make -j10 built/wasm32/binutils-gdb
    - name: make gcc-preliminary
      run: make -j10 built/wasm32/gcc-preliminary
    - name: make glibc
      run: make -j10 built/wasm32/glibc
    - name: make gcc
      run: make -j10 built/wasm32/gcc
    - name: make ncurses
      run: make -j10 built/wasm32/ncurses
    - name: make bash
      run: make -j10 built/wasm32/bash
    - name: make wabt
      run: make -j10 built/common/wabt
    - name: make binaryen
      run: make -j10 built/common/binaryen
    - name: make all
      run: make -j10 all
