name: make all
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  all:
    name: make all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: git submodule update --init --recursive --
    - name: make all
      run: make -j10 all
