name: daily
on:
  push:
    branches: [ master, daily, wasm ]
  pull_request:
    branches: [ master, daily, wasm ]
jobs:
  binutils:
    name: binutils
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj10 daily-binutils!
  gcc-preliminary:
    name: gcc-preliminary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj10 daily-gcc-preliminary!
  glibc:
    name: glibc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj10 daily-glibc!
  gcc:
    name: gcc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj10 daily-gcc!
  ncurses:
    name: ncurses
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj10 github/install/file-slurp
    - run: make -kj10 daily-ncurses!
  bash:
    name: bash
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj10 github/install/file-slurp
    - run: make -kj10 daily-bash!
  coreutils:
    name: coreutils
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj10 github/install/file-slurp
    - run: make -kj10 daily-coreutils!
  miniperl:
    name: miniperl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj10 github/install/file-slurp
    - run: make -kj10 tools/bin/dyninfo
    - run: make -kj10 daily-miniperl!
