name: gcc-testsuite
on:
  push:
    branches: [ master, daily, wasm ]
  pull_request:
    branches: [ master, daily, wasm ]
jobs:
  gcc-c-torture-compile:
    name: gcc.c-torture/compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.c-torture/compile/compile.exp.{daily-dejanew}!
    - run: make GITHUB=1 -kj10 artifact-push!

  gcc-c-torture-execute:
    name: gcc.c-torture/execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.c-torture/execute/execute.exp.{daily-dejanew}!
    - run: make GITHUB=1 -kj10 artifact-push!

  gcc-c-torture-execute-builtins:
    name: gcc.c-torture/execute/builtins
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.c-torture/execute/builtins/builtins.exp.{daily-dejanew}!
    - run: make GITHUB=1 -kj10 artifact-push!

  gcc-c-torture-execute-ieee:
    name: gcc.c-torture/execute/ieee
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.c-torture/execute/ieee/ieee.exp.{daily-dejanew}!
    - run: make GITHUB=1 -kj10 artifact-push!

  gcc-dg-dg:
    name: gcc.dg/dg.exp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/dg.exp.{daily-dejanew}!
    - run: make GITHUB=1 -kj10 artifact-push!

  gcc-dg-misc:
    name: gcc.dg/*
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/atomic/atomic.exp.{daily-dejanew}!
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/charset/charset.exp.{daily-dejanew}!
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/debug/debug.exp.{daily-dejanew}!
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/debug/dwarf2/dwarf2.exp.{daily-dejanew}!
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/debug/format/format.exp.{daily-dejanew}!
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/debug/lto/lto.exp.{daily-dejanew}!
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/debug/tls/tls.exp.{daily-dejanew}!
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/debug/tm/tm.exp.{daily-dejanew}!
    - run: JS=$(pwd)/bin/js WASMDIR=$(pwd) PATH=$PATH:$(pwd)/wasm32-unknown-none/bin make GITHUB=1 -kj10 gcc.dg/debug/weak/weak.exp.{daily-dejanew}!
    - run: make GITHUB=1 -kj10 artifact-push!

  pack-artifacts:
    name: pack artifacts
    runs-on: ubuntu-latest
    needs:
    - gcc-c-torture-compile
    - gcc-c-torture-execute
    - gcc-c-torture-execute-builtins
    - gcc-c-torture-execute-ieee
    - gcc-dg-dg
    - gcc-dg-misc
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make GITHUB=1 -kj10 gcc-testsuites-pack!
    - run: make GITHUB=1 -kj10 artifact-push!
