name: gcc-testsuite
on:
  push:
    branches: [ master ]
jobs:
  gcc:
    name: gcc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Set env variables
      uses: ./github/env/
    - run: make -kj10 gcc-testsuite!
