name: WASM32
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  binaryen:
    name: binaryen
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: check out subrepos/binaryen
      run: git submodule update --depth=1 --single-branch --init subrepos/binaryen
    - name: build
      run: make built/common/binaryen

  wabt:
    name: wabt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: check out subrepos/wabt
      run: git submodule update --depth=1 --single-branch --recursive --init subrepos/wabt
    - name: build
      run: make built/common/wabt

  jsshell:
    name: jsshell
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: wget http://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/jsshell-linux-x86_64.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: jsshell-linux-x86_64.zip
        path: jsshell-linux-x86_64.zip

  wasm32-js:
    name: wasm32.js
    runs-on: ubuntu-latest
    steps:
    - name: Install cpanm
      run: sudo apt-get install cpanminus
    - name: Install File::Slurp
      run: cpanm File::Slurp
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Build wasm32.js
      run: make js/wasm32.js
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: wasm32.js
        path: js/wasm32.js

  binutils:
    name: binutils
    runs-on: ubuntu-latest
    steps:
    - name: install texinfo, bison, flex
      run: sudo apt-get install texinfo bison flex
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Check out subrepos/binutils-gdb
      run: git submodule update --depth=1 --single-branch --init subrepos/binutils-gdb
    - name: artifact timestamp
      run: touch artifact.stmp
    - name: build
      run: make -kj10 built/wasm32/binutils-gdb
    - name: Create artifact
      run: tar cvf wasm32-unknown-none-binutils.tar wasm32-unknown-none built
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: wasm32-unknown-none-binutils.tar
        path: wasm32-unknown-none-binutils.tar

  gcc-preliminary:
    name: gcc (preliminary)
    runs-on: ubuntu-latest
    needs: binutils
    steps:
    - name: install texinfo, bison, flex
      run: sudo apt-get install texinfo bison flex
    - name: install GCC dependencies
      run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Check out subrepos/gcc
      run: git submodule update --depth=1 --single-branch --init subrepos/gcc
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-binutils.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: artifact timestamp
      run: touch artifact.stmp
    - name: build preliminary GCC
      run: make -kj10 built/wasm32/gcc-preliminary
    - name: Create artifact
      run: tar cf wasm32-unknown-none-gcc-preliminary.tar wasm32-unknown-none built
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: wasm32-unknown-none-gcc-preliminary.tar
        path: wasm32-unknown-none-gcc-preliminary.tar

  glibc:
    name: glibc
    runs-on: ubuntu-latest
    needs: gcc-preliminary
    steps:
    - name: install texinfo, bison, flex
      run: sudo apt-get install texinfo bison flex
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Check out subrepos/glibc
      run: git submodule update --depth=1 --single-branch --init subrepos/glibc
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-binutils.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc-preliminary.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc-preliminary.tar/wasm32-unknown-none-gcc-preliminary.tar
    - name: artifact timestamp
      run: touch artifact.stmp
    - name: build glibc
      run: make -kj10 built/wasm32/glibc
    - name: Create artifact
      run: tar cf wasm32-unknown-none-glibc.tar wasm32-unknown-none built
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: wasm32-unknown-none-glibc.tar
        path: wasm32-unknown-none-glibc.tar
    - name: Generate WASM modules
      run: make wasm/ld.wasm wasm/libc.wasm
    - name: Upload ld.wasm
      uses: actions/upload-artifact@v1
      with:
        name: ld.wasm
        path: wasm/ld.wasm
    - name: Upload libc.wasm
      uses: actions/upload-artifact@v1
      with:
        name: libc.wasm
        path: wasm/libc.wasm

  gcc:
    name: gcc
    runs-on: ubuntu-latest
    needs: glibc
    steps:
    - name: install texinfo, bison, flex
      run: sudo apt-get install texinfo bison flex
    - name: install GCC dependencies
      run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Check out gcc subrepo
      run: git submodule update --depth=1 --single-branch --init subrepos/gcc
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-binutils.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc-preliminary.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-glibc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc-preliminary.tar/wasm32-unknown-none-gcc-preliminary.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-glibc.tar/wasm32-unknown-none-glibc.tar
    - name: artifact timestamp
      run: touch artifact.stmp
    - name: build final GCC
      run: make -kj10 built/wasm32/gcc
    - name: Create artifact
      run: tar cf wasm32-unknown-none-gcc.tar wasm32-unknown-none built
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: wasm32-unknown-none-gcc.tar
        path: wasm32-unknown-none-gcc.tar

  ncurses:
    name: ncurses
    runs-on: ubuntu-latest
    needs: gcc
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Check out ncurses
      run: git submodule update --depth=1 --single-branch --init subrepos/ncurses
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-binutils.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc-preliminary.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-glibc.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc-preliminary.tar/wasm32-unknown-none-gcc-preliminary.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-glibc.tar/wasm32-unknown-none-glibc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc.tar/wasm32-unknown-none-gcc.tar
    - name: artifact timestamp
      run: touch artifact.stmp
    - name: build ncurses
      run: make -kj10 built/wasm32/ncurses
    - name: Create artifact
      run: tar cf wasm32-unknown-none-ncurses.tar wasm32-unknown-none built
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: wasm32-unknown-none-ncurses.tar
        path: wasm32-unknown-none-ncurses.tar

  _001-hello-world-o:
    name: Hello World (assemble)
    runs-on: ubuntu-latest
    needs: gcc-preliminary
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-binutils.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc-preliminary.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc-preliminary.tar/wasm32-unknown-none-gcc-preliminary.tar
    - name: Assemble
      run: ./wasm32-unknown-none/bin/wasm32-unknown-none-as -Iwasm32-unknown-none/lib/gcc/wasm32-unknown-none/11.0.0/gas-macros/ -c -o 001-hello-world.o tests/001-hello-world/hello-world.S
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: 001-hello-world.o
        path: 001-hello-world.o

  _001-hello-world-exe:
    name: Hello World (preliminary C version)
    runs-on: ubuntu-latest
    needs:
      - glibc
      - _001-hello-world-o
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-binutils.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc-preliminary.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-glibc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc-preliminary.tar/wasm32-unknown-none-gcc-preliminary.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-glibc.tar/wasm32-unknown-none-glibc.tar
    - name: Compile
      run: ./wasm32-unknown-none/bin/wasm32-unknown-none-gcc ./tests/002-hello-world/hello-world.c -o 001-hello-world.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: 001-hello-world.exe
        path: 001-hello-world.exe

  _003-hello-world-exe:
    name: Hello World (final C version)
    runs-on: ubuntu-latest
    needs: gcc
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-binutils.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc-preliminary.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-glibc.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc-preliminary.tar/wasm32-unknown-none-gcc-preliminary.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-glibc.tar/wasm32-unknown-none-glibc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc.tar/wasm32-unknown-none-gcc.tar
    - name: Compile
      run: ./wasm32-unknown-none/bin/wasm32-unknown-none-gcc ./tests/003-hello-world/hello-world.c -o 003-hello-world.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: 003-hello-world.exe
        path: 003-hello-world.exe

  _001-hello-world-run:
    name: Hello World (run)
    runs-on: ubuntu-latest
    needs:
      - _001-hello-world-wasm
      - jsshell
      - wasm32-js
      - glibc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: Download jsshell artifact
        uses: actions/download-artifact@v1
        with:
          name: jsshell-linux-x86_64.zip
      - name: Unpack jsshell
        run: unzip jsshell-linux-x86_64.zip/jsshell-linux-x86_64.zip -d bin
      - name: Download wasm32.js artifact
        uses: actions/download-artifact@v1
        with:
          name: wasm32.js
      - run: mkdir js
      - name: Unpack wasm32
        run: cp wasm32.js/wasm32.js js/wasm32.js
      - name: Download 001-hello-world.wasm artifact
        uses: actions/download-artifact@v1
        with:
          name: 001-hello-world.wasm
      - name: download ld.wasm
        uses: actions/download-artifact@v1
        with:
          name: ld.wasm
      - name: download libc.wasm
        uses: actions/download-artifact@v1
        with:
          name: libc.wasm
      - name: directory shuffle
        run: mkdir wasm-dirs && mv *.wasm wasm-dirs
      - name: copy *.wasm
        run: cp wasm-dirs/*.wasm/*.wasm .
      - name: Run
        run: WASMDIR=. ./bin/js ./js/wasm32.js ./001-hello-world.wasm/001-hello-world.wasm

  _001-hello-world-wasm:
    name: Hello World (WASM)
    runs-on: ubuntu-latest
    needs:
    - _001-hello-world-exe
    - gcc
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Download gcc
      uses: actions/download-artifact@v1
      with:
        name: wasm32-unknown-none-binutils.tar
    - name: Download gcc
      uses: actions/download-artifact@v1
      with:
        name: wasm32-unknown-none-gcc-preliminary.tar
    - name: Download gcc
      uses: actions/download-artifact@v1
      with:
        name: wasm32-unknown-none-glibc.tar
    - name: Download gcc
      uses: actions/download-artifact@v1
      with:
        name: wasm32-unknown-none-gcc.tar
    - name: Unpack wasm32
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: Unpack wasm32
      run:
        tar xf wasm32-unknown-none-gcc-preliminary.tar/wasm32-unknown-none-gcc-preliminary.tar
    - name: Unpack wasm32
      run:
        tar xf wasm32-unknown-none-glibc.tar/wasm32-unknown-none-glibc.tar
    - name: Unpack wasm32
      run:
        tar xf wasm32-unknown-none-gcc.tar/wasm32-unknown-none-gcc.tar
    - name: Download 001-hello-world.exe
      uses: actions/download-artifact@v1
      with:
        name: 001-hello-world.exe
    - name: Build wasmrewrite
      run: make bin/wasmrewrite
    - name: Build wasmssect
      run: make bin/wasmsect
    - name: wasmify
      run: bash -x ./wasmify/wasmify-executable 001-hello-world.exe/001-hello-world.exe > 001-hello-world.wasm
    - name: Upload 001-hello-world.wasm
      uses: actions/upload-artifact@v1
      with:
        name: 001-hello-world.wasm
        path: 001-hello-world.wasm

  bash:
    name: bash
    runs-on: ubuntu-latest
    needs:
      # bash fails to compile unless ncurses is there, too.
      - ncurses
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Check out bash
      run: git submodule update --depth=1 --single-branch --init subrepos/bash
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-binutils.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc-preliminary.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-glibc.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-ncurses.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc-preliminary.tar/wasm32-unknown-none-gcc-preliminary.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-glibc.tar/wasm32-unknown-none-glibc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc.tar/wasm32-unknown-none-gcc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-ncurses.tar/wasm32-unknown-none-ncurses.tar
    - name: Build
      run: make -kj10 built/wasm32/bash
#    - name: build WASM
#      run: make -kj10 wasm/bash.wasm
#    - name: Upload WASM
#      uses: actions/upload-artifact@v1
#      with:
#        name: bash.wasm
#        path: wasm/bash.wasm

  emacs:
    name: emacs
    runs-on: ubuntu-latest
    needs:
      - ncurses
    steps:
    - name: install texinfo, bison, flex
      run: sudo apt-get install texinfo bison flex
    - uses: actions/checkout@v2
      with:
        submodules: false
    - name: Check out emacs
      run: git submodule update --depth=1 --single-branch --init subrepos/emacs
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-binutils.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc-preliminary.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-glibc.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-gcc.tar
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name:
          wasm32-unknown-none-ncurses.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-binutils.tar/wasm32-unknown-none-binutils.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc-preliminary.tar/wasm32-unknown-none-gcc-preliminary.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-glibc.tar/wasm32-unknown-none-glibc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-gcc.tar/wasm32-unknown-none-gcc.tar
    - name: Unpack
      run:
        tar xf wasm32-unknown-none-ncurses.tar/wasm32-unknown-none-ncurses.tar
    - name: build
      run: make -kj10 built/wasm32/emacs
    - name: Build WASM
      run: make -kj10 wasm/emacs.wasm
    - name: Upload WASM
      uses: actions/upload-artifact@v1
      with:
        name: emacs.wasm
        path: wasm/emacs.wasm
