name: GCC, final version (WASM32)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install texinfo, bison, flex
      run: sudo apt-get install texinfo bison flex
    - name: install GCC dependencies
      run: sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: build binutils
      run: make -kj5 build/wasm32/binutils-gdb.make
    - name: build preliminary GCC
      run: make -kj5 build/wasm32/gcc-preliminary.make
    - name: build glibc
      run: make -kj5 build/wasm32/glibc.make
    - name: build final GCC
      run: make -kj5 build/wasm32/gcc.make
