name: Binutils (WASM32)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - name: make
      run: make -kj5 build/wasm32/binutils-gdb.make
