name: Binutils (WASM32)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install texinfo, bison
      run: sudo apt-get install texinfo bison
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: make
      run: make -kj5 build/wasm32/binutils-gdb.make
